# -*- coding: utf-8 -*-
"""Assigment_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rhUATMLI0iqrATNYImaNt_uZHEW0iTQv
"""

from google.colab import drive, auth
auth.authenticate_user()
import requests
gcloud_token = !gcloud auth print-access-token
drive.mount('/content/drive', force_remount=True)

with open('/content/drive/My Drive/Colab Notebooks/Assignment_4_Script.py') as infile:
    exec(infile.read())

excelfile = '/content/drive/My Drive/Data/Assignment_5_Data_and_Template.xlsx'

"""### Importing data"""

sheets=getSheetNames(excelfile);sheets

N=950
d=2
C=3

training=(readExcel(excelfile,
                  sheetname='Data',
                  startrow=2,
                  endrow=(N+1),
                  startcol=1,
                  endcol=2)).astype(float);training.shape

X=np.array(training);print(X[:15,:]);

from sklearn.mixture import GaussianMixture
gm = GaussianMixture(n_components=3, covariance_type='full').fit(X)
labels = gm.predict(X)
plt.scatter(X[:, 0], X[:, 1], c=labels, cmap='viridis');
probs = gm.predict_proba(X); print(probs[:15,:])

print(labels[:15]);print(labels.shape)

np.unique(labels)

# if probs[1]~=1 Child (C)
# if probs[0]~=1 Female (F)
# if probs[2]~=1 Male (M)
def GMLabels2ClassLabels(GMlabels):
  n=np.size(labels,axis=0)
  str_labels=np.zeros((n), dtype=str)
  NC=0
  NF=0
  NM=0
  for i in range(n):
    if GMlabels[i]==0:
      str_labels[i]='F'
      NF+=1
    elif GMlabels[i]==1:
      str_labels[i]='C'
      NC+=1
    else:
      str_labels[i]='M'
      NM+=1
  return [str_labels, NC, NF, NM]

def GMLabels2WinnerProbs(ClassLabels, GMprobs):
  n=np.size(labels,axis=0)
  winner_probs=np.zeros((n), dtype=float)
  for i in range(n):
    if ClassLabels[i]=='C':
      winner_probs[i]=GMprobs[i,1]
    elif ClassLabels[i]=='F':
      winner_probs[i]=GMprobs[i,0]
    else:
      winner_probs[i]=GMprobs[i,2]
  return winner_probs*100

[class_labels, NC, NF, NM] =GMLabels2ClassLabels(labels); 
winner_confidence=GMLabels2WinnerProbs(class_labels,probs)
print(class_labels[:15]);
print(winner_confidence[:15]);
print('Number of Children:', NC);
print('Number of Females:', NF);
print('Number of Males:', NM);
print(N==NC+NF+NM);

"""### Writing to template"""

writeExcelData(class_labels,excelfile,'Results',2,1)
writeExcelData(winner_confidence,excelfile,'Results',2,2)
print("Labels and confidences have been written!")

writeExcelData([NM],excelfile,'Results',2,6)
writeExcelData([NF],excelfile,'Results',3,6)
writeExcelData([NC],excelfile,'Results',4,6)
print("Counts for males, females, and children have been written!")